### ISSUE TITLE
Problem running partition.py

### ISSUE THREAD

**Issue by hsnguyen** [jgurtowski/nanocorr#10]
Hi, I've got bug running the partition step with the error displayed as below:

Traceback (most recent call last):
          File "partition.py", line 32, in <module>
            for record in input_data:
          File "/home/sonnguyen/soft/nanocorr/nanocorr_venv/local/lib/python2.7/site-packages/jbio/fasta.py", line 17, in record_iterator
            if not first or not first.startswith(">"):
        AttributeError: 'FastaRecord' object has no attribute 'startswith' 

Plz help. Thanks.

**Comment by jgurtowski** [comment]
This should have been fixed a while ago, can you update jbio?

**Comment by hsnguyen** [comment]
Yeah. sorry I forgot to close the issue. Everything went fine. THanks.
