### ISSUE TITLE
Pbdagcon installation issue

### ISSUE THREAD

**Issue by NathanGuy14** [jgurtowski/nanocorr#2]
Hi,
Not sure if this is the right place for this, but I thought you should know that running the command "pip install git+https://github.com/PacificBiosciences/pbdagcon" in the virtual environment results in the error "AttributeError: 'module' object has no attribute 'Distutils'" for me.   Here is the full text of pip.log in case that helps.  I also get the same error when jptools tries to install pbdagcon.

 Am I doing something wrong?  Any advice you can give would be appreciated.

Thanks,
Nathan

---

/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/bin/pip run on Tue Jan 13 13:45:40 2015
Downloading/unpacking git+https://github.com/PacificBiosciences/pbdagcon

  Cloning https://github.com/PacificBiosciences/pbdagcon to /tmp/pip-j3EW7Q-build

  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/PacificBiosciences/pbdagcon /tmp/pip-j3EW7Q-build
  Running setup.py egg_info for package from git+https://github.com/PacificBiosciences/pbdagcon

```
zip_safe flag not set; analyzing archive contents...



Installed /tmp/pip-j3EW7Q-build/setuptools_cython-0.2.1-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-j3EW7Q-build/setup.py", line 29, in <module>

    "pbcore >= 0.6.3"

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 225, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 258, in finalize_options

    ep.load()(self, ep.name, value)

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load

    entry = __import__(self.module_name, globals(),globals(), ['__name__'])

  File "/tmp/pip-j3EW7Q-build/setuptools_cython-0.2.1-py2.7.egg/setuptools_cython.py", line 21, in <module>

    class build_cython(Cython.Distutils.build_ext, object):

AttributeError: 'module' object has no attribute 'Distutils'

Complete output from command python setup.py egg_info:

zip_safe flag not set; analyzing archive contents...
```

Installed /tmp/pip-j3EW7Q-build/setuptools_cython-0.2.1-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/pip-j3EW7Q-build/setup.py", line 29, in <module>

```
"pbcore >= 0.6.3"
```

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

```
_setup_distribution = dist = klass(attrs)
```

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 225, in **init**

```
_Distribution.__init__(self,attrs)
```

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in **init**

```
self.finalize_options()
```

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 258, in finalize_options

```
ep.load()(self, ep.name, value)
```

  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load

```
entry = __import__(self.module_name, globals(),globals(), ['__name__'])
```

  File "/tmp/pip-j3EW7Q-build/setuptools_cython-0.2.1-py2.7.egg/setuptools_cython.py", line 21, in <module>

```
class build_cython(Cython.Distutils.build_ext, object):
```

AttributeError: 'module' object has no attribute 'Distutils'

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-j3EW7Q-build

Exception information:
Traceback (most recent call last):
  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/gdlab/ncrook/bin/nanocorr-master/nanocorr_ve/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/**init**.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-j3EW7Q-build

**Comment by NathanGuy14** [comment]
Just FYI, running the following commands allowed the pbdagcon installation to proceed:

pip install --upgrade setuptools 
pip install --upgrade distribute
pip install --upgrade buildutils

Hope this helps anyone else with the same problem.
